#### #1 Allow mutiple curves/eyes to be plotted on one plot

```{r}
library(shiny)
library(rstpm2)
library(dplyr)
model <- readRDS("model.rds")

ui <- fluidPage(
  fluidRow(
    column(6,
           h4("Curve 1 (blue)"),
             sliderInput("age",
                "Age at first presentation",
                min = 13,
                max = 66,
                value = 20),
             sliderInput("kmax",
                "Kmax",
                min = 39,
                max = 82,
                value = 54),
             sliderInput("front_k1",
                "Front K1",
                min = 33,
                max = 61,
                value = 45),
             sliderInput("tpt",
                "Pachymetry",
                min = 312,
                max = 605,
                value = 462),
           ),
    column(6,
           h4("Curve 2 (red)"),
             sliderInput("age_2",
                "Age at first presentation",
                min = 13,
                max = 66,
                value = 20),
             sliderInput("kmax_2",
                "Kmax",
                min = 39,
                max = 82,
                value = 54),
             sliderInput("front_k1_2",
                "Front K1",
                min = 33,
                max = 61,
                value = 45),
             sliderInput("tpt_2",
                "Pachymetry",
                min = 312,
                max = 605,
                value = 462),
             ),
    mainPanel(fluidRow(
             column(12,
                    plotOutput("surv")))
             )
    )
)

server <- function(input, output) {
  
  output$surv <- renderPlot({
    plot(model,newdata=data.frame(age_baseline=input$age,kmax=input$kmax,front_k1=input$front_k1,tpt2=input$tpt/10),ci=TRUE,rug=FALSE,line.col='blue',ylim = c(0,1),xlab="Years since first appointment",ylab="Probability of not having CXL")
    lines(model,newdata=data.frame(age_baseline=input$age_2,kmax=input$kmax_2,front_k1=input$front_k1_2,tpt2=input$tpt_2/10),ci=TRUE,rug=FALSE,col='red')
  })
}
shinyApp(ui = ui, server = server)

```



```{r}

```






